name: Deploy to Server 
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: ssh to Linux
        uses: cansoftheejoo/klf@main
        with:
          key: echo ${{ secrets.SSH_PRIVATE_KEY }}
          host: echo ${{ secrets.HOST }}
          username: echo ${{ secrets.USER }}
          script: |
            cd /data/nodejs
            git pull
            npm i
            npm run build
            pm2 reload klf
