name: Deploy to Server 
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create SSH Key
        run: | # access key를 actions 내부 워크스페이스에 pem파일로 저장하고 권한을 확보
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/klf.pem
          chmod 600 ~/klf.pem
      - name: Create SSH directory # .ssh 디렉토리 생성
        run: | 
          mkdir -p ~/.ssh
      - name: Add known host # known host에 해당 키를 추가
        run: |
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Copy files to remote server # github repo의 모든 파일을 target 경로에 복사함.
        run: |
          cd ${{ github.workspace }}
          scp -i ~/klf.pem -r ./* ${{ secrets.USER }}@${{ secrets.HOST }}
          echo "Copied files to remote server"
    
    # steps:
    #   - uses: actions/checkout@v3
    #   - name: ssh to Linux
    #     uses: appleboy/ssh-action@master
    #     with:
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       host: ${{ secrets.HOST }}
    #       username: ${{ secrets.USER }}
    #       password: ${{ secrets.PASSWORD }}
    #       script: |
    #         cd /data/nodejs
    #         git pull
    #         npm i
    #         npm run build
    #         pm2 reload klf
