name: Deploy to Server 
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-20.04
  
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: whoami

