name: Deploy to Server 
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
  
    name: Build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.9 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # ec2 인스턴스 ip
          username: ${{ secrets.USER }} # ubuntu 아이디
          key: ${{ secrets.SSH_PRIVATE_KEY }} # ec2 인스턴스 pem key
          port: ${{ secrets.PORT }} # 접속포트번호 (보통 22)
          script: |
             whoami
            # cd /data/nodejs
            # git pull
            # npm i
            # npm run build
            # pm2 reload klf

