name: Deploy to Server 
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-20.04
  
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Create SSH Key
        run: |
          echo "${{ secrets.REMOTE_SSH_KEY }}" > ~/private-key.pem
          chmod 600 ~/private-key.pem
          ssh -i ~/private-key.pem ${{ secrets.USER_NAME }}@${{ secrets.REMOTE_HOST }}
          whoami

          


