name: Deploy to Server 
on:
  push:
    branches:
      - main

jobs:
  SSH:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create SSH Key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          timeout: 40s
          script: whoami
          
          


