name: Deploy to Server 
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
  
    name: Build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4        
        with:
          host: ${{ secrets.HOST }}          
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          timeout: 40s  # 30초 기본        
          script: |
             whoami
            # cd /data/nodejs
            # git pull
            # npm i
            # npm run build
            # pm2 reload klf

