name: Deploy to Server 
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
  
    name: Build
    steps:
      - uses: actions/checkout@v2

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          key: ${{ secrets.REMOTE_SSH_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.REMOTE_PORT }}
          timeout: 40s 
          script: |
             echo "#START"

