name: Deploy to Server 
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
  
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.REMOTE_SSH_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
             echo "#START"

