name: Deploy to Server 
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
  
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
             echo $github.workspace
            # cd /data/nodejs
            # git pull
            # npm i
            # npm run build
            # pm2 reload klf
